USE DATABASE TRUST_DB;

CREATE OR REPLACE PROCEDURE CORE.LOAD_TRANSACTIONS()
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
  MERGE INTO CORE.TRANSACTIONS AS T
  USING (
    SELECT *, 'RETAIL' AS SOURCE_SYSTEM FROM RAW.RETAIL_TRANSACTIONS
    UNION ALL
    SELECT *, 'WHOLESALE' AS SOURCE_SYSTEM FROM RAW.WHOLESALE_TRANSACTIONS
  ) AS S
  ON T.TRANSACTION_ID = S.TRANSACTION_ID
  WHEN MATCHED THEN UPDATE SET
    T.TRANSACTION_DATE = S.TRANSACTION_DATE,
    T.PARTNER_ID = S.PARTNER_ID,
    T.TRANSACTION_TYPE = S.TRANSACTION_TYPE,
    T.AMOUNT = S.AMOUNT,
    T.CURRENCY = S.CURRENCY,
    T.SOURCE_SYSTEM = S.SOURCE_SYSTEM,
    T.UPDATED_AT = S.UPDATED_AT
  WHEN NOT MATCHED THEN INSERT (
    TRANSACTION_ID, TRANSACTION_DATE, PARTNER_ID, TRANSACTION_TYPE,
    AMOUNT, CURRENCY, SOURCE_SYSTEM, UPDATED_AT
  ) VALUES (
    S.TRANSACTION_ID, S.TRANSACTION_DATE, S.PARTNER_ID, S.TRANSACTION_TYPE,
    S.AMOUNT, S.CURRENCY, S.SOURCE_SYSTEM, S.UPDATED_AT
  );

  RETURN 'TRANSACTIONS LOAD COMPLETED';
END;
$$;
