USE DATABASE TRUST_DB;

-- Embeddings are generated by the application/Snowpark layer using
-- the configured Snowflake Cortex embedding model and stored in
-- AI.DOCUMENT_CHUNKS.EMBEDDING.

-- Example pattern (model and dimensions must match the selected model):
-- UPDATE AI.DOCUMENT_CHUNKS
-- SET EMBEDDING = SNOWFLAKE.CORTEX.EMBED_TEXT_768(
--   'snowflake-arctic-embed-m-v1.5', CHUNK_TEXT
-- );

-- Cortex LLM calls are intentionally kept in the application/workflow
-- layer so model selection can be controlled by YAML configuration.
