-- AI TRUST Engine
-- 00_setup.sql
-- Replace placeholders before execution.

CREATE WAREHOUSE IF NOT EXISTS IDENTIFIER('${TRUST_WH}')
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

CREATE DATABASE IF NOT EXISTS IDENTIFIER('${TRUST_DB}');

CREATE SCHEMA IF NOT EXISTS IDENTIFIER('${TRUST_DB}.RAW');
CREATE SCHEMA IF NOT EXISTS IDENTIFIER('${TRUST_DB}.CORE');
CREATE SCHEMA IF NOT EXISTS IDENTIFIER('${TRUST_DB}.AI');
CREATE SCHEMA IF NOT EXISTS IDENTIFIER('${TRUST_DB}.FORECAST');
CREATE SCHEMA IF NOT EXISTS IDENTIFIER('${TRUST_DB}.GOVERNANCE');
CREATE SCHEMA IF NOT EXISTS IDENTIFIER('${TRUST_DB}.METADATA');

-- Optional: set role/warehouse explicitly in the deployment session.
-- USE ROLE <deployment_role>;
-- USE WAREHOUSE IDENTIFIER('${TRUST_WH}');
-- USE DATABASE IDENTIFIER('${TRUST_DB}');
