-- AI TRUST Engine
-- 01_file_formats.sql

CREATE FILE FORMAT IF NOT EXISTS IDENTIFIER('${TRUST_DB}.RAW.FF_PARQUET')
  TYPE = PARQUET;

CREATE FILE FORMAT IF NOT EXISTS IDENTIFIER('${TRUST_DB}.RAW.FF_CSV')
  TYPE = CSV
  SKIP_HEADER = 1
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  NULL_IF = ('', 'NULL', 'null');

CREATE FILE FORMAT IF NOT EXISTS IDENTIFIER('${TRUST_DB}.RAW.FF_JSON')
  TYPE = JSON
  STRIP_OUTER_ARRAY = FALSE;
