-- AI TRUST Engine
-- 03_raw_tables.sql

CREATE TABLE IF NOT EXISTS IDENTIFIER('${TRUST_DB}.RAW.RETAIL_TRANSACTIONS') (
  TRANSACTION_ID STRING,
  TRANSACTION_DATE DATE,
  PARTNER_ID STRING,
  TRANSACTION_TYPE STRING,
  AMOUNT NUMBER(18,2),
  CURRENCY STRING,
  UPDATED_AT TIMESTAMP_NTZ,
  SOURCE_FILE STRING,
  INGESTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS IDENTIFIER('${TRUST_DB}.RAW.WHOLESALE_TRANSACTIONS') (
  TRANSACTION_ID STRING,
  TRANSACTION_DATE DATE,
  PARTNER_ID STRING,
  TRANSACTION_TYPE STRING,
  AMOUNT NUMBER(18,2),
  CURRENCY STRING,
  UPDATED_AT TIMESTAMP_NTZ,
  SOURCE_FILE STRING,
  INGESTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS IDENTIFIER('${TRUST_DB}.RAW.CONTRACT_FILES') (
  DOCUMENT_ID STRING,
  CONTRACT_ID STRING,
  PARTNER_ID STRING,
  FILE_NAME STRING,
  FILE_PATH STRING,
  MIME_TYPE STRING,
  EFFECTIVE_DATE DATE,
  EXPIRY_DATE DATE,
  INGESTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
