-- AI TRUST Engine
-- 04_core_tables.sql

CREATE TABLE IF NOT EXISTS IDENTIFIER('${TRUST_DB}.CORE.TRANSACTIONS') (
  TRANSACTION_ID STRING NOT NULL,
  TRANSACTION_DATE DATE,
  PARTNER_ID STRING,
  TRANSACTION_TYPE STRING,
  AMOUNT NUMBER(18,2),
  CURRENCY STRING,
  SOURCE_SYSTEM STRING,
  UPDATED_AT TIMESTAMP_NTZ,
  CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  UPDATED_INGESTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS IDENTIFIER('${TRUST_DB}.CORE.CONTRACTS') (
  CONTRACT_ID STRING NOT NULL,
  PARTNER_ID STRING,
  DOCUMENT_ID STRING,
  EFFECTIVE_DATE DATE,
  EXPIRY_DATE DATE,
  STATUS STRING,
  CONTRACT_VERSION STRING,
  SOURCE_FILE STRING,
  CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
