-- AI TRUST Engine
-- 05_ai_tables.sql

CREATE TABLE IF NOT EXISTS IDENTIFIER('${TRUST_DB}.AI.DOCUMENTS') (
  DOCUMENT_ID STRING NOT NULL,
  CONTRACT_ID STRING,
  PARTNER_ID STRING,
  FILE_NAME STRING,
  SOURCE_PATH STRING,
  EXTRACTED_TEXT STRING,
  PAGE_COUNT NUMBER,
  EXTRACTION_METHOD STRING,
  OCR_USED BOOLEAN DEFAULT FALSE,
  EFFECTIVE_DATE DATE,
  EXPIRY_DATE DATE,
  CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS IDENTIFIER('${TRUST_DB}.AI.DOCUMENT_CHUNKS') (
  CHUNK_ID STRING NOT NULL,
  DOCUMENT_ID STRING,
  CONTRACT_ID STRING,
  PARTNER_ID STRING,
  SECTION STRING,
  PAGE_NUMBER NUMBER,
  CHUNK_INDEX NUMBER,
  CHUNK_TEXT STRING,
  CHUNKING_STRATEGY STRING,
  EMBEDDING_MODEL STRING,
  EMBEDDING VECTOR(FLOAT, 768),
  CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS IDENTIFIER('${TRUST_DB}.AI.RAG_AUDIT') (
  RUN_ID STRING,
  QUERY STRING,
  CONTRACT_ID STRING,
  PARTNER_ID STRING,
  RETRIEVED_CHUNKS VARIANT,
  MODEL_NAME STRING,
  PROMPT_VERSION STRING,
  RESPONSE_TEXT STRING,
  CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
