-- AI TRUST Engine
-- 06_forecast_tables.sql

CREATE TABLE IF NOT EXISTS IDENTIFIER('${TRUST_DB}.FORECAST.DEMAND_FEATURES') (
  PARTNER_ID STRING,
  FEATURE_DATE DATE,
  LAG_1 NUMBER(18,4),
  LAG_3 NUMBER(18,4),
  LAG_12 NUMBER(18,4),
  ROLLING_MEAN_7 NUMBER(18,4),
  ROLLING_MEAN_30 NUMBER(18,4),
  CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS IDENTIFIER('${TRUST_DB}.FORECAST.DEMAND_FORECAST') (
  FORECAST_ID STRING,
  PARTNER_ID STRING,
  FORECAST_DATE DATE,
  HORIZON_DAYS NUMBER,
  MODEL_NAME STRING,
  PREDICTED_DEMAND NUMBER(18,4),
  PREDICTED_REVENUE NUMBER(18,2),
  PREDICTED_ROYALTY NUMBER(18,2),
  MODEL_VERSION STRING,
  RUN_ID STRING,
  CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
