-- AI TRUST Engine
-- 07_governance_tables.sql

CREATE TABLE IF NOT EXISTS IDENTIFIER('${TRUST_DB}.GOVERNANCE.APPROVALS') (
  APPROVAL_ID STRING,
  RUN_ID STRING,
  CONTRACT_ID STRING,
  PARTNER_ID STRING,
  RECOMMENDATION_TYPE STRING,
  RECOMMENDATION VARIANT,
  REQUIRED_ROLE STRING,
  STATUS STRING DEFAULT 'PENDING',
  REVIEWER STRING,
  REVIEW_COMMENT STRING,
  CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  REVIEWED_AT TIMESTAMP_NTZ
);

CREATE TABLE IF NOT EXISTS IDENTIFIER('${TRUST_DB}.GOVERNANCE.AUDIT_LOG') (
  AUDIT_ID STRING,
  RUN_ID STRING,
  WORKFLOW_NAME STRING,
  EVENT_TYPE STRING,
  ACTOR STRING,
  INPUT_REFERENCE VARIANT,
  OUTPUT_REFERENCE VARIANT,
  MODEL_NAME STRING,
  PROMPT_VERSION STRING,
  STATUS STRING,
  MESSAGE STRING,
  CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
