-- AI TRUST Engine
-- 08_metadata_tables.sql

CREATE TABLE IF NOT EXISTS IDENTIFIER('${TRUST_DB}.METADATA.PIPELINE_RUNS') (
  RUN_ID STRING,
  PIPELINE_NAME STRING,
  PIPELINE_VERSION STRING,
  ENVIRONMENT STRING,
  STATUS STRING,
  SOURCE_SYSTEM STRING,
  RECORDS_READ NUMBER,
  RECORDS_WRITTEN NUMBER,
  RECORDS_REJECTED NUMBER,
  STARTED_AT TIMESTAMP_NTZ,
  FINISHED_AT TIMESTAMP_NTZ,
  ERROR_MESSAGE STRING
);

CREATE TABLE IF NOT EXISTS IDENTIFIER('${TRUST_DB}.METADATA.AI_MODEL_METADATA') (
  MODEL_NAME STRING,
  MODEL_PROVIDER STRING,
  MODEL_TYPE STRING,
  MODEL_VERSION STRING,
  PURPOSE STRING,
  CONFIG VARIANT,
  ACTIVE BOOLEAN DEFAULT TRUE,
  CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS IDENTIFIER('${TRUST_DB}.METADATA.DOCUMENT_METADATA') (
  DOCUMENT_ID STRING,
  CONTRACT_ID STRING,
  SOURCE_SYSTEM STRING,
  DOMAIN STRING,
  PIPELINE_VERSION STRING,
  EMBEDDING_MODEL STRING,
  CHUNKING_STRATEGY STRING,
  SOURCE_FILE STRING,
  CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
