-- AI TRUST Engine
-- 09_validation_views.sql

CREATE OR REPLACE VIEW IDENTIFIER('${TRUST_DB}.METADATA.V_TRANSACTION_NULL_CHECKS') AS
SELECT
  COUNT_IF(TRANSACTION_ID IS NULL) AS NULL_TRANSACTION_ID,
  COUNT_IF(TRANSACTION_DATE IS NULL) AS NULL_TRANSACTION_DATE,
  COUNT_IF(PARTNER_ID IS NULL) AS NULL_PARTNER_ID,
  COUNT_IF(AMOUNT IS NULL) AS NULL_AMOUNT
FROM IDENTIFIER('${TRUST_DB}.CORE.TRANSACTIONS');

CREATE OR REPLACE VIEW IDENTIFIER('${TRUST_DB}.METADATA.V_TRANSACTION_DUPLICATES') AS
SELECT
  PARTNER_ID,
  TRANSACTION_DATE,
  TRANSACTION_TYPE,
  AMOUNT,
  COUNT(*) AS DUPLICATE_COUNT
FROM IDENTIFIER('${TRUST_DB}.CORE.TRANSACTIONS')
GROUP BY PARTNER_ID, TRANSACTION_DATE, TRANSACTION_TYPE, AMOUNT
HAVING COUNT(*) > 1;

CREATE OR REPLACE VIEW IDENTIFIER('${TRUST_DB}.METADATA.V_INVALID_TRANSACTION_TYPES') AS
SELECT TRANSACTION_TYPE, COUNT(*) AS RECORD_COUNT
FROM IDENTIFIER('${TRUST_DB}.CORE.TRANSACTIONS')
WHERE TRANSACTION_TYPE NOT IN (
  'INCOME', 'RETURN', 'APPEASEMENT', 'ADJUSTMENT',
  'CREDIT', 'DEBIT', 'CANCELLATION'
)
GROUP BY TRANSACTION_TYPE;
