-- AI TRUST Engine
-- 10_cortex_search.sql
-- Cortex Search syntax and supported parameters can change by Snowflake release.
-- Validate this template against the target account before production deployment.

-- Example deployment pattern:
-- CREATE OR REPLACE CORTEX SEARCH SERVICE <DB>.AI.CONTRACT_SEARCH
--   ON CHUNK_TEXT
--   ATTRIBUTES CONTRACT_ID, PARTNER_ID, SECTION, PAGE_NUMBER
--   WAREHOUSE = <SEARCH_WAREHOUSE>
--   TARGET_LAG = '1 hour'
--   AS (
--     SELECT
--       CHUNK_TEXT,
--       CONTRACT_ID,
--       PARTNER_ID,
--       SECTION,
--       PAGE_NUMBER
--     FROM <DB>.AI.DOCUMENT_CHUNKS
--   );

-- Keep the exact service definition account-specific because Cortex Search
-- capabilities, syntax, and indexing options evolve.
