-- AI TRUST Engine
-- 11_tasks.sql
-- Tasks are intentionally templates. Connect them to the actual Python/Snowpark
-- procedures after those procedures are implemented.

CREATE TASK IF NOT EXISTS IDENTIFIER('${TRUST_DB}.METADATA.TASK_FORECASTING_DAILY')
  WAREHOUSE = IDENTIFIER('${TRUST_WH}')
  SCHEDULE = 'USING CRON 0 2 * * * UTC'
  AS
    INSERT INTO IDENTIFIER('${TRUST_DB}.METADATA.PIPELINE_RUNS')
      (RUN_ID, PIPELINE_NAME, PIPELINE_VERSION, ENVIRONMENT, STATUS, STARTED_AT)
    SELECT UUID_STRING(), 'forecasting', '1.0', '${TRUST_ENV}', 'TRIGGERED', CURRENT_TIMESTAMP();

CREATE TASK IF NOT EXISTS IDENTIFIER('${TRUST_DB}.METADATA.TASK_CONTRACT_EXPIRY_DAILY')
  WAREHOUSE = IDENTIFIER('${TRUST_WH}')
  SCHEDULE = 'USING CRON 0 3 * * * UTC'
  AS
    INSERT INTO IDENTIFIER('${TRUST_DB}.METADATA.PIPELINE_RUNS')
      (RUN_ID, PIPELINE_NAME, PIPELINE_VERSION, ENVIRONMENT, STATUS, STARTED_AT)
    SELECT UUID_STRING(), 'contract_expiry_check', '1.0', '${TRUST_ENV}', 'TRIGGERED', CURRENT_TIMESTAMP();

-- Enable only after validating the task actions:
-- ALTER TASK IDENTIFIER('${TRUST_DB}.METADATA.TASK_FORECASTING_DAILY') RESUME;
-- ALTER TASK IDENTIFIER('${TRUST_DB}.METADATA.TASK_CONTRACT_EXPIRY_DAILY') RESUME;
