USE DATABASE TRUST_DB;

CREATE TABLE IF NOT EXISTS AI.AI_METADATA (
  RUN_ID STRING,
  WORKFLOW_NAME STRING,
  MODEL_PROVIDER STRING,
  MODEL_NAME STRING,
  EMBEDDING_MODEL STRING,
  PROMPT_VERSION STRING,
  SOURCE_DOCUMENT STRING,
  RETRIEVAL_TOP_K INTEGER,
  ENVIRONMENT STRING,
  STATUS STRING,
  STARTED_AT TIMESTAMP_NTZ,
  COMPLETED_AT TIMESTAMP_NTZ,
  METADATA VARIANT
);
