USE DATABASE TRUST_DB;

CREATE TABLE IF NOT EXISTS CORE.CONTRACTS (
  CONTRACT_ID STRING,
  PARTNER_ID STRING,
  DOCUMENT_NAME STRING,
  DOCUMENT_PATH STRING,
  EFFECTIVE_DATE DATE,
  EXPIRY_DATE DATE,
  COUNTRY STRING,
  CURRENCY STRING,
  STATUS STRING,
  VERSION STRING,
  CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  UPDATED_AT TIMESTAMP_NTZ
);
