USE DATABASE TRUST_DB;

CREATE TABLE IF NOT EXISTS AI.DOCUMENT_CHUNKS (
  CHUNK_ID STRING,
  CONTRACT_ID STRING,
  DOCUMENT_NAME STRING,
  CHUNK_TEXT STRING,
  CHUNK_INDEX INTEGER,
  PAGE_NUMBER INTEGER,
  SECTION STRING,
  PARTNER_ID STRING,
  EFFECTIVE_DATE DATE,
  EXPIRY_DATE DATE,
  EMBEDDING VECTOR(FLOAT, 768),
  CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
