USE DATABASE TRUST_DB;

CREATE TABLE IF NOT EXISTS FORECAST.DEMAND_FORECAST (
  FORECAST_DATE DATE,
  PARTNER_ID STRING,
  HORIZON_DAYS INTEGER,
  MODEL_NAME STRING,
  PREDICTED_DEMAND NUMBER(18,4),
  PREDICTED_REVENUE NUMBER(18,2),
  PREDICTED_ROYALTY NUMBER(18,2),
  MODEL_VERSION STRING,
  RUN_ID STRING,
  CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
