USE DATABASE TRUST_DB;

CREATE TABLE IF NOT EXISTS RAW.RETAIL_TRANSACTIONS (
  TRANSACTION_ID STRING,
  TRANSACTION_DATE DATE,
  PARTNER_ID STRING,
  TRANSACTION_TYPE STRING,
  AMOUNT NUMBER(18,2),
  CURRENCY STRING,
  UPDATED_AT TIMESTAMP_NTZ,
  SOURCE_FILE STRING,
  INGESTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS RAW.WHOLESALE_TRANSACTIONS LIKE RAW.RETAIL_TRANSACTIONS;
