USE DATABASE TRUST_DB;

CREATE TABLE IF NOT EXISTS CORE.TRANSACTIONS (
  TRANSACTION_ID STRING,
  TRANSACTION_DATE DATE,
  PARTNER_ID STRING,
  TRANSACTION_TYPE STRING,
  AMOUNT NUMBER(18,2),
  CURRENCY STRING,
  SOURCE_SYSTEM STRING,
  UPDATED_AT TIMESTAMP_NTZ,
  CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  CONSTRAINT CK_TRANSACTION_TYPE CHECK (
    TRANSACTION_TYPE IN ('INCOME','RETURN','APPEASEMENT','ADJUSTMENT','CREDIT','DEBIT','CANCELLATION')
  )
);
